version: "3.8"

services: 
  api:
    image: eassbhhtgu/identity-server:latest
    entrypoint: bash -c "/usr/sbin/update-ca-certificates && dotnet IdentityServer.WebApplication.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_HTTPS_PORT: "443"
      ASPNETCORE_URLS: https://+
      ApiScopes:0:Name: networkdiscovery
      Clients:0:AllowedGrantTypes:0: client_credentials
      Clients:0:AllowedScopes:0: networkdiscovery
      Clients:0:ClientId: elgatoapi
      Clients:0:ClientSecrets:0:Value: h/6VJnVASjaniqTj78ov08ew7isdXH0O+Lo0fxhIZy4=
      Kestrel:Certificates:Default:KeyPath: /run/secrets/localhost.key
      Kestrel:Certificates:Default:Path: /run/secrets/localhost.crt
      ReverseProxy:Routes:baget-route:ClusterId: baget-cluster
      ReverseProxy:Routes:baget-route:Match:Hosts:0: baget
      ReverseProxy:Clusters:baget-cluster:Destinations:baget-destination:Address: https://baget:30443/
    ports:
    - 443:443/tcp
    secrets:
    - source: localhost.crt
    - source: localhost.key
    - source: ca.crt
      target: /usr/local/share/ca-certificates/ca.crt

secrets:
  ca.crt:
    file: ${USERPROFILE}\.aspnet\https\ca.crt
  localhost.crt:
    file: ${USERPROFILE}\.aspnet\https\identityserver.crt
  localhost.key:
    file: ${USERPROFILE}\.aspnet\https\identityserver.key
