version: "3.8"

services: 
  api:
    image: eassbhhtgu/identity-server:latest
    entrypoint: bash -c "/usr/sbin/update-ca-certificates && dotnet IdentityServer.WebApplication.dll"
    environment:
      ApiScopes:0:Name: default
      Clients:0:AllowedGrantTypes:0: client_credentials
      Clients:0:AllowedScopes:0: default
      Clients:0:ClientId: client1
      # secret1
      Clients:0:ClientSecrets:0:Value: WxFhjC5EAnh30M0JIe0Wa58Xb1BYf8kedTTdKUbbd9Y=
      Kestrel:Certificates:Default:KeyPath: /usr/local/share/localhost.key
      Kestrel:Certificates:Default:Path: /usr/local/share/localhost.crt
    ports:
    - 443:443/tcp
    secrets:
    - source: localhost_crt
      target: /usr/local/share/localhost.crt
    - source: localhost_key
      target: /usr/local/share/localhost.key
    - source: ca.crt
      target: /usr/local/share/ca-certificates/ca.crt

secrets:
  ca.crt:
    file: ${USERPROFILE}\.aspnet\https\ca.crt
  localhost_crt:
    file: ${USERPROFILE}\.aspnet\https\localhost.crt
  localhost_key:
    file: ${USERPROFILE}\.aspnet\https\localhost.key
